import = [
   # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/night-owl.toml"
]

shell = "/usr/bin/fish"
[scrolling]
history = 10000
multiplier = 8 

[window]
opacity = 0.92 
title = "Alacritty Terminal Emulator"
dynamic_title = false

[[keyboard.bindings]]
action = "Paste"
key = "v"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "c"
mods = "Control"


# live_config_reload = true
